### ISSUE TITLE
Update SRS and Use Case Document

### ISSUE THREAD

**Issue by BrodyWilliams** [aluminiumi/RaiderNAV#51]

**Comment by aluminiumi** [comment]
This task still requires several things:
1. The new mockups
2. Updated/corrected use case diagrams for user stories that have been completed
3. Updates relevant to new product backlog entries (if any), including
    a. Requirements
    b. Use cases
4. A regenerated table of contents

**Comment by aluminiumi** [comment]
This task still requires:
    -A regenerated table of contents
    -Updates relevant to new product backlog entries, including
        a. Requirements
        b. Use cases

New mockups, corrected use case diagrams for completed user stories, and sweeping (but not comprehensive) updates to all other use cases have been completed.
